---
title: "lncRNA analysis of mCRPC He et al Nature Medicine 2021"
output: html_notebook
---
#Load libraries
```{r}

library(tidyverse)
library(Seurat)
library(Hmisc)
library(ggrepel)
library(EnhancedVolcano)
library(msigdbr)
library(EnsDb.Hsapiens.v86)
library(Matrix)
library(ggpubr)
library(tidytext)
library(cowplot)
library(ComplexHeatmap)
library(circlize)

options(ggrepel.max.overlaps = Inf)


```

#Read in scRNAseq data
```{r}
#Read in count data for tumors only in csv - convert to seurat object
anno <- read.table("/Users/ds/Desktop/scRNA_datasets/scp_metadata.tsv", sep = "\t", header = T)  

anno <- anno[-1,]
row.names(anno) <- anno$NAME

tpm <- read.csv(file = "/Users/ds/Desktop/scRNA_datasets/scp_tpm.tsv", sep = "\t", header = TRUE)

tpm <- tpm[!duplicated(tpm$GENE),]
row.names(tpm) <- tpm$GENE
tpm <- tpm[,-1]
colnames(tpm) <- as.character(1:length(anno$NAME) -1)

bmet <- CreateSeuratObject(tpm, meta.data = anno)


bmet <- SetAssayData(object = bmet, slot = "data", new.data = Matrix(as.matrix(log1p(tpm)), sparse = T))
meta <- read.csv(file = "/Users/ds/Desktop/scRNA_datasets/scp_tpm_celltypes.csv")


bmet@meta.data <- cbind(bmet@meta.data, meta)
tx <- read.csv(file = "/Users/ds/Desktop/scRNA_datasets/He_NatureMedicine_tx.csv")
tx <- tx %>% dplyr::filter(has.scRNA == "True")


tx <- inner_join(bmet@meta.data, tx) %>% dplyr::select(c(biopsy, prior.enzalutamide, prior.abiraterone, prior.taxane, prior.platinum, prior.sipuleucel.T))

bmet@meta.data <- cbind(bmet@meta.data, tx)

saveRDS(object = bmet, file = "/Users/ds/Desktop/scRNA_datasets/He_mCRPC.rds")

```



#Download lncRNAs hg38 from cellranger
```{r}

bmet <- readRDS(file = "/Users/ds/Desktop/scRNA_datasets/He_scRNA/He_mCRPC.rds")

all_genes <- read_tsv(file = "/Users/ds/Desktop/projects/data/anno//hg38.genes.meta.tsv")

linc <- all_genes %>% dplyr::filter(gene.biotype == "lncRNA")
pcg <- all_genes %>% dplyr::filter(gene.biotype == "protein_coding")

linc

mat <- GetAssayData(object = bmet)



id <- intersect(row.names(mat), linc$gene.name)




dim(mat[id,])[1] / dim(linc)[1]

bmet$organ__ontology_label
mat["PCAT14",]
Idents(bmet) <- "supercluster.for.LDSC.SEG"

View(dss)

bmet
```



#LncRNA markers for cells
```{r}

markers <- FindAllMarkers(object = bmet[row.names(bmet) %in% linc$gene.name,], only.pos = T, verbose = T)
pcg_markers <- FindAllMarkers(object = bmet[row.names(bmet) %in% pcg$gene.name], only.pos = T, verbose = T)

markers %>% dplyr::filter(pct.1 > 0.1 & p_val_adj < 0.1 & avg_log2FC> 1)  %>% dplyr::filter(cluster == 'tumor')


markers <- markers  %>% dplyr::filter(pct.1 > 0.1 & p_val_adj < 0.1 & avg_log2FC> 1) #Filter percent diff, logFC, and adj P value
markers <- markers[!duplicated(markers$gene),]#Filter duplicates



pcg_markers <- pcg_markers %>%  dplyr::filter(pct.1 > 0.1 & p_val_adj < 0.1 & avg_log2FC> 1) 

pcg_markers <- pcg_markers %>%  arrange(-avg_log2FC) %>% group_by(cluster) %>% slice_head(n = 2)   #Filter percent diff, logFC, and adj P value


pcg_markers <- pcg_markers[!duplicated(pcg_markers$gene),]#Filter duplicates

View(final_markers)

bmet@assays$RNA@counts

```

#Filter markers using Chen et al
```{r}
valid <- read.table(file = "/Users/ds/Desktop/projects/lncRNA/data/Manual.Marker.modify.txt", header = T)

#Filter prostate
other_markers <- valid %>% dplyr::filter(is.na(Epithelia) & (!is.na(BCell) | !is.na(DC)   | !is.na(Endothelia) | !is.na(Fibroblast) | !is.na(Macrophage) | !is.na(MastCell) | !is.na(Myofib) |  !is.na(Neutrophil) | !is.na(pDC) | !is.na(PlasmaCell) | !is.na(TCell)   )) 
  
other_markers <- other_markers  %>% dplyr::select(-ends_with(".p_val_adj")) %>% gather(key  = "Cell", value = "logFC", -markers.gene) %>% group_by(Cell) %>% dplyr::filter(logFC>1) %>% .$markers.gene %>% unique()



a <- markers  %>% dplyr::filter(cluster == "tumor") %>% dplyr::filter(!gene %in% other_markers) %>% arrange(-avg_log2FC) 

#Filter B cell lineage
other_markers <- valid %>% dplyr::filter( (is.na(BCell) & is.na(PlasmaCell))   & (!is.na(Epithelia) | !is.na(DC)   | !is.na(Endothelia) | !is.na(Fibroblast) | !is.na(Macrophage) | !is.na(MastCell) | !is.na(Myofib) |  !is.na(Neutrophil) | !is.na(pDC) |  !is.na(TCell)   )) 

other_markers <- other_markers  %>% dplyr::select(-ends_with(".p_val_adj")) %>% gather(key  = "Cell", value = "logFC", -markers.gene) %>% group_by(Cell) %>% dplyr::filter(logFC>1) %>% .$markers.gene %>% unique()


b <- markers  %>% dplyr::filter(cluster == "B lineage" ) %>% dplyr::filter(! gene %in% other_markers) %>% arrange(-avg_log2FC) 



#Filter NK/T cell
other_markers <- valid %>% dplyr::filter(is.na(TCell) & (!is.na(Epithelia) | !is.na(DC)   | !is.na(Endothelia) | !is.na(Fibroblast) | !is.na(Macrophage) | !is.na(MastCell) | !is.na(Myofib) |  !is.na(Neutrophil) | !is.na(pDC) | !is.na(PlasmaCell) | !is.na(BCell)   )) 

other_markers <- other_markers  %>% dplyr::select(-ends_with(".p_val_adj")) %>% gather(key  = "Cell", value = "logFC", -markers.gene) %>% group_by(Cell) %>% dplyr::filter(logFC>1) %>% .$markers.gene %>% unique()


c <- markers  %>% dplyr::filter(cluster == "NK/T") %>% dplyr::filter(! gene %in% other_markers) %>% arrange(-avg_log2FC) 


#Filter neutrophil cell
other_markers <- valid %>% dplyr::filter(is.na(Neutrophil) & (!is.na(Epithelia) | !is.na(DC)   | !is.na(Endothelia) | !is.na(Fibroblast) | !is.na(Macrophage) | !is.na(MastCell) | !is.na(Myofib) |  !is.na(TCell) | !is.na(pDC) | !is.na(PlasmaCell) | !is.na(BCell)   )) 

other_markers <- other_markers  %>% dplyr::select(-ends_with(".p_val_adj")) %>% gather(key  = "Cell", value = "logFC", -markers.gene) %>% group_by(Cell) %>% dplyr::filter(logFC>1) %>% .$markers.gene %>% unique()


d <- markers  %>% dplyr::filter(cluster == "neutrophil") %>% dplyr::filter(! gene %in% other_markers) %>% arrange(-avg_log2FC) 


#Filter monocyte/macrophage cell
other_markers <- valid %>% dplyr::filter(is.na(Macrophage) & (!is.na(Epithelia) | !is.na(DC)   | !is.na(Endothelia) | !is.na(Fibroblast) | !is.na(Neutrophil) | !is.na(MastCell) | !is.na(Myofib) |  !is.na(TCell) | !is.na(pDC) | !is.na(PlasmaCell) | !is.na(BCell)   )) 

other_markers <- other_markers  %>% dplyr::select(-ends_with(".p_val_adj")) %>% gather(key  = "Cell", value = "logFC", -markers.gene) %>% group_by(Cell) %>% dplyr::filter(logFC>1) %>% .$markers.gene %>% unique()


e <- markers  %>% dplyr::filter(cluster == "monocyte/macrophage" ) %>% dplyr::filter(! gene %in% other_markers) %>% arrange(-avg_log2FC) 


#Filter erythroid cell
f <- markers  %>% dplyr::filter(cluster == "erythroid" ) %>% arrange(-avg_log2FC) 


filt_markers <- rbind(a,b,c,d,e,f)


```


#Filter markers using Kfoury et al
```{r}
bmcrpc <- readRDS(file = "/Users/ds/Desktop/scRNA_datasets/seurat/Kfoury_bmCRPC_scRNA.rds")


Idents(bmcrpc) <- "cells"
valid_kfoury <-FindAllMarkers(object = bmcrpc[row.names(bmcrpc) %in% linc$gene.name,], only.pos = T, verbose = T)



valid_kfoury <- valid_kfoury  %>% dplyr::filter(pct.1 > 0.1 & p_val_adj < 0.1 & avg_log2FC> 1) %>%  arrange(-avg_log2FC) 
valid_kfoury <- valid_kfoury[!duplicated(valid_kfoury$gene),]#Filter duplicates


#Filter prostate
other_markers <- valid_kfoury %>% dplyr::filter(cluster != "Tumor")  %>% .$gene
a <- filt_markers %>% dplyr::filter(cluster == "tumor") %>% dplyr::filter( !gene %in% other_markers )



#Filter NK/T cells
other_markers <- valid_kfoury %>% dplyr::filter(! cluster %in% c("CTL-1", "CTL-2", "NK", "NKT", "CD4+ Naive" ,"Treg Active","Th1/17","Treg Resting","CD8+ Naive"))  %>% .$gene
b <- filt_markers %>% dplyr::filter(cluster == "NK/T") %>% dplyr::filter( !gene %in% other_markers )

#Filter B lineage cells
other_markers <- valid_kfoury %>% dplyr::filter(! cluster %in% c("Mature B","memBcell" ,"Pro-B","Immature B cells"))  %>% .$gene
c <- filt_markers %>% dplyr::filter(cluster == "B lineage") %>% dplyr::filter( !gene %in% other_markers )

#Filter monocyte/macrophage cells
other_markers <- valid_kfoury %>% dplyr::filter(! cluster %in% c("Mono3" , "mDC"  ,"TIM" ,"TAM" ,"Mono2"  ,"Mono1","Monocyte prog")) %>%  .$gene
d <- filt_markers %>% dplyr::filter(cluster == "monocyte/macrophage") %>% dplyr::filter( !gene %in% other_markers )


#Filter erythroid cells
other_markers <- valid_kfoury %>% dplyr::filter(! cluster %in% c("Erythroid")) %>% .$gene
e <- filt_markers %>% dplyr::filter(cluster == "erythroid") %>% dplyr::filter( !gene %in% other_markers )


#No granulocytes in this dataset
f <- filt_markers %>% dplyr::filter(cluster == "neutrophil")

final_markers <- rbind(a,c,b,f,d,e)


View(final_markers)
```


```{r}
compare_markers <- rbind(dplyr::filter(pcg_markers, cluster == 'tumor'), a,dplyr::filter(pcg_markers, cluster == "B lineage") , c,dplyr::filter(pcg_markers, cluster == "NK/T"),b,dplyr::filter(pcg_markers, cluster == "neutrophil"),f,dplyr::filter(pcg_markers, cluster == "monocyte/macrophage"),d,dplyr::filter(pcg_markers, cluster == "erythroid"),e)


compare_markers <- rbind(dplyr::filter(pcg_markers, cluster == 'tumor'), dplyr::filter(final_markers, cluster == 'tumor'),dplyr::filter(pcg_markers, cluster == "B lineage") , dplyr::filter(final_markers, cluster == 'B lineage'),dplyr::filter(pcg_markers, cluster == "NK/T"),dplyr::filter(final_markers, cluster == 'NK/T'),dplyr::filter(pcg_markers, cluster == "neutrophil"),dplyr::filter(final_markers, cluster == 'neutrophil'),dplyr::filter(pcg_markers, cluster == "monocyte/macrophage"),dplyr::filter(final_markers, cluster == 'monocyte/macrophage'),dplyr::filter(pcg_markers, cluster == "erythroid"),dplyr::filter(final_markers, cluster == 'erythroid'))


```


#Plot markers
```{r}

set.seed(111)
pca_lncrna <- final_markers %>%  dplyr::filter(cluster == "tumor") %>% arrange(-avg_log2FC)  %>% .$gene

notpca_lncrna <- final_markers %>% dplyr::filter(!gene %in% pca_lncrna) %>% arrange(-avg_log2FC) %>% .$gene
#notpca_lncrna_ds <- sample(notpca_lncrna, length(pca_lncrna))
notpca_lncrna_ds <- sample(notpca_lncrna, length(notpca_lncrna))

other_lncrna <- linc %>% dplyr::filter(!gene.name %in% final_markers$gene) %>% .$gene.name

#other_lncrna_ds <- sample(other_lncrna, length(pca_lncrna))
other_lncrna_ds <- sample(other_lncrna, length(notpca_lncrna))




```


```{r}
other_lncrna
linc
mcrpc_rna <- read.table(file = "/Users/ds/Desktop/projects/data/rna/mCRPC_RNA_CPM_genename.txt", header = T)

mcrpc_rna <- mcrpc_rna %>% dplyr::filter(Genename %in% c(pca_lncrna, notpca_lncrna)) %>% mutate(Group = ifelse(Genename %in% pca_lncrna, "Prostate lncRNA", "Non prostate lncRNA")) %>% gather(key = "ID", value = "GEX", -c(Genename, Group)) %>% mutate(GEX = log1p(GEX)) 

mcrpc %>% ggplot(aes(x = Group, y = GEX)) + geom_boxplot()

stat.test <- mcrpc_rna %>% wilcox_test(formula = GEX ~ Group) %>% add_significance()   
p2 <- ggboxplot(mcrpc_rna, x = "Group", y = "GEX", fill = viridis::cividis(10)[5])
stat.test <- stat.test %>% add_xy_position(x = "Group")
p2 <- p2 + 
  stat_pvalue_manual(stat.test, label = "p") +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1)))
stat.test
```


```{r}

bmet <- ScaleData(object = bmet, features = final_markers$gene)


pdf("/Users/ds/Desktop/plot.pdf", height = 15, width = 10)

DoHeatmap(object = bmet, features = final_markers$gene, assay = "RNA", slot = "scale.data",   )+ theme(axis.text.y = element_text(size = 0)) 
dev.off()


```

#Compare lncRNA markers with PCG markers
```{r}
top <-compare_markers  %>% arrange(-avg_log2FC) %>% group_by(cluster)  %>% dplyr::slice(1:7) %>% .$gene



names(top) <- compare_markers  %>% arrange(-avg_log2FC) %>% group_by(cluster)  %>% dplyr::slice(1:7) %>% .$cluster



pdf("/Users/ds/Desktop/plot.pdf", width = 15, height = 15)
DotPlot(object = bmet, features = top, group.by = "supercluster.for.LDSC.SEG") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() + theme(axis.text.y.left  = element_text(color = rep(c('red', 'red', 'blue', 'blue', 'blue', 'blue', 'blue'), 5)))
dev.off()




write.table(x = final_markers, file = "/Users/ds/Desktop/projects/lncRNA/results/final_markers_mCRPC_He.txt", quote = F, sep = "\t", row.names = F, col.names = T)


final_markers <- read.table(file = "/Users/ds/Desktop/projects/lncRNA/results/final_markers_mCRPC_He.txt", header = T, sep = "\t")

```


#UMAP Plotting
```{r}


seurat_pipeline <- function(object, ndims, seed, resolution){
  
  #Data already normalized 
    FindVariableFeatures(object = object, nfeatures = 2000) %>% 
    ScaleData() %>%
    RunPCA() %>% 
    RunUMAP(dims = 1:ndims, reduction = "pca") %>% 
    FindNeighbors(reduction = "pca", dims = 1:ndims) %>% 
    FindClusters(resolution = resolution, algorithm = 1, random.seed =seed) %>% 
    return()
  
}

tumor <- subset(bmet, supercluster.for.LDSC.SEG == 'tumor')
bmet <- seurat_pipeline(object = bmet, ndims = 40, seed = 123, 0.5)


tumor <- seurat_pipeline(object = tumor, ndims = 40, seed = 123, 0.5)

Idents(bmet) <- "supercluster.for.LDSC.SEG"
top

pdf("/Users/ds/Desktop/plot.pdf", width = 10)
FeaturePlot(object = bmet, features =c("COLCA1", "FTX"), label = T, repel = T, label.size = 3)
dev.off()
final_markers

UMAPPlot(object = tumor, label = T, repel = T)
tumor$AR.regulon <- tumor[tni.get(object = rtni,what = "regulons" )$AR,] %>% GetAssayData() %>% colMeans()


pdf("/Users/ds/Desktop/plot.pdf", width = 5)
FeaturePlot(object = tumor, features = c("AR.regulon", "COLCA1"), ncol = 1)
dev.off()
```





#Plot heatmaps for specific lncRNAs
```{r}
mcrpc_rna <- read.table(file = "/Users/ds/Desktop/projects/data/rna/mCRPC_RNA_counts_genename.txt", header = T)
mcrpc_rna <- mcrpc_rna[!duplicated(mcrpc_rna$Genename),]




row.names(mcrpc_rna) <- mcrpc_rna$Genename
mcrpc_rna <- mcrpc_rna[,-1]
mcrpc_rna <- edgeR::cpm(mcrpc_rna, log = T) %>% t() %>% data.frame()#Log normalize for heatmap
#mcrpc_rna <- mcrpc_rna %>% t() %>% data.frame()#Counts for DEG analysis
row.names(mcrpc_rna) <- gsub("\\.", "-",  x = row.names(mcrpc_rna))
mcrpc_rna <- mcrpc_rna %>% mutate(cases = row.names(.), batch = "mCRPC")



anno <- read.table("/Users/ds/Desktop/projects/data/anno/202009_deepRNAseq_sample_full.txt", header =T)


anno
anno <- anno %>% dplyr::select(c(sample_id, wgs_id, biopsy_site, disease_type_SIG_GEX, ID_patient, AR,tumor_purity_rna, RB1 )) 


cf <- read.table("/Users/ds/Desktop/projects/BME_analysis/results/CIBERSORTx_Job33_Adjusted.txt", sep = "\t", header = T)
cf$sample_id <- gsub("\\.", "-", cf$Mixture)
row.names(cf) <- cf$Mixture

cf <- inner_join(x = cf, y = anno, by  = c("sample_id" = "sample_id"))



row.names(cf) <- cf$sample_id


cf <- na.omit(cf)#Omit samples without WGS data
cf <- cf %>% dplyr::filter(disease_type_SIG_GEX =='adeno')


ehmr <- read_csv(file = "/Users/ds/Desktop/projects/lncRNA/data/ehmr.csv", col_names = T)
ehmr <- ehmr %>% dplyr::filter(type == "HMR")%>% group_by(symbol) %>% arrange(cor) %>% group_by(symbol) %>% dplyr::slice(1)

ehmr <- ehmr %>% dplyr::filter(symbol %in% pca_lncrna) %>% mutate(Coord = paste0(chrom, ".", start, ".", end))




hmr <- read.table(file = "/Users/ds/Desktop/projects/data/bs/all.mcrpc.hmr.txt", header = T)
hmr <- hmr[!duplicated(hmr$Coord),]



hmr <- hmr %>% merge(ehmr) %>% mutate(HMR = paste0(symbol, ".", type)) %>% dplyr::select(c(HMR, starts_with("DTB")))
row.names(hmr) <- hmr$HMR
hmr <- hmr[-1] %>% t() %>% data.frame() %>% mutate(wgs_id  = gsub(pattern = "\\.", replacement = "-", x = row.names(.)))


cna <- read.table(file = "/Users/ds/Desktop/projects/data/wgs/2018_04_15_matrix_CN_integer_symbol_copycat.txt", header = T)

cna <- cna %>% dplyr::filter(IDENTIFIER %in% pca_lncrna) %>% mutate(CopyNumber = paste0(IDENTIFIER, ".CN"))
row.names(cna) <- cna$CopyNumber
cna <- dplyr::select(cna, -c(CopyNumber, IDENTIFIER)) %>% t() %>% data.frame() %>% mutate(wgs_id  = gsub(pattern = "\\.", replacement = "-", x = row.names(.)))




```


```{r}
df <- data.frame(mcrpc_rna[, "cases", drop = F],mcrpc_rna[,c(colnames(mcrpc_rna) %in% pca_lncrna)]) %>% inner_join(cf, by = c("cases" = "sample_id")) %>% merge(hmr) %>% merge(cna)




goi <- c("PCAT14", "SCHLAP1", "COLCA1", "PART1", "PCAT1")
df

df <- df[,c(goi, "cases", "AR", paste0(goi, ".HMR"), paste0(goi, ".CN"))]  %>% mutate(AR = ifelse(AR == 3, "Gain", "WT")) 
df
```


```{r}


df <- df %>% arrange(PCAT14)  

row.names(df) <- df$cases

col_fun1 = colorRamp2(c(0, 100), c("grey", "blue"))

col_fun2 = colorRamp2(c(0, 3), c("grey", "purple"))

column_ha = HeatmapAnnotation( PCAT14 = anno_barplot(df[,"PCAT14"]  ), HMR = df[,"PCAT14.HMR"], CNA = df[,"PCAT14.CN"], simple_anno_size = unit(2, "cm"), height = unit(8,"cm"), col = list(PCAT14 = "black", HMR = col_fun1, CNA = col_fun2 ))

pdf("/Users/ds/Desktop/plot.pdf")
Heatmap(matrix = t(df[,c( "AR"), drop = F]), top_annotation = column_ha, height = unit(2, "cm"), col = colorRampPalette(c("navy", "grey"))(2), show_column_names = F, name = "Mutational.status")
dev.off()



```


```{r}
df
df <- df %>% arrange(COLCA1)  

row.names(df) <- df$cases

col_fun1 = colorRamp2(c(0, 100), c("grey", "blue"))

col_fun2 = colorRamp2(c(0, 3), c("grey", "purple"))

column_ha = HeatmapAnnotation( COLCA1 = anno_barplot(df[,"COLCA1"]  ), HMR = df[,"COLCA1.HMR"], simple_anno_size = unit(2, "cm"), height = unit(5,"cm"), col = list(COLCA1 = "black", HMR = col_fun1))

pdf("/Users/ds/Desktop/plot.pdf")
Heatmap(matrix = t(df[,c( "AR"), drop = F]), top_annotation = column_ha, height = unit(2, "cm"), show_column_names = F, name = "Mutational.status", col = colorRampPalette(c("navy", "grey"))(2))
dev.off()

df
```

```{r}


m1 <- lm(COLCA1 ~ COLCA1.HMR, data = df)
m2 <- lm(COLCA1 ~ AR + COLCA1.HMR, data = df)

lm(SCHLAP1 ~ AR + SCHLAP1.HMR, data = df) %>% summary()

lm(PCAT14 ~ AR + PCAT14.HMR + PCAT14.CN, data = df) %>% summary()

ggplot(df, aes(x = COLCA1.HMR, y = COLCA1, color = AR)) + geom_smooth(method = 'lm') + ggpubr::stat_cor() + geom_point()

anova(m1,m2)


```

