---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(Seurat)
library(rstatix)
library(ggpubr)
```


```{r}


#Function to obtain random sample of cell ids for specified samples and celltypes 
GetCellID <- function(object, celltype, number) {
  id <- object@meta.data %>% dplyr::filter( cluster %in% celltype) %>% .$cells 
  return(sample(x = id, size = number, replace = T) )
}



#Function to generate CPM expression for cell ids from data
GetCPM <- function(object, celltype, ...) {
  
  cellids <- GetCellID(object = object, celltype = celltype, ...)
  counts <- GetAssayData(object = object, slot = "counts")[, WhichCells(object = object, cells = cellids)] %>% Matrix(sparse = T)
  rownames(counts) <- GetAssayData(object = object, slot = "counts") %>% rownames()
  
  #CPM normalize data
    counts <-  RelativeCounts(counts, scale.factor = 10^6, verbose = F) 
  counts %>% as.data.frame()
  return(counts)
}


#Method to create reference by upsampling tumor fraction and downsampling the remaining immune/strmal cells while preserving their original proportions
MakeReference <- function(object, tumor_bias, number_of_cells, ...){
  
  
  #Create df of celltypes and proportions
  df <- object@meta.data  %>% dplyr::select("cluster") %>% table() %>% prop.table() %>% as.data.frame()
  colnames(df) <- c("Cell", "Freq")
  #Set tumor frequency based on tumor purity and the rest as proportions times the remaining fraction
  df <- df  %>% mutate(Freq = ifelse(Cell != "Tumor.", Freq * (1-tumor_bias), tumor_bias))

    #Set seed for reproducibility
  set.seed(123)
  
  #Loop over cells in df and cbind the resulting GEPs into reference
  ref <- do.call(cbind,lapply(1:nrow(df), FUN = function(i){
  
  print(paste0("Processing celltype: ", df[i,1]))
  
  #Obtain CPM for number of celltypes
  gep <- GetCPM(object = object, celltype = df[i,1],  number = (number_of_cells * df[i,2]), ...)
  gep <- data.frame(gep)
  #Set colnames as celltypes replicates
  colnames(gep) <- c(paste0(df[i,1], c(1:(ncol(gep)))))
  return(gep)

  }))
  
  
  #Return full reference with df of proportions
  return(list(Ref = ref, Freq= df))

  
  }
    
    
  



```


```{r}

anno <- read.table("/Users/ds/Desktop/projects/BME_analysis/data/202009_deepRNAseq_sample_full.txt", header =T)


```


```{r}
#Load scRNAseq into Seurat object
scrna <- readRDS(file = "/Users/ds/Desktop/scRNA_datasets/seurat/Kfoury_bmCRPC_scRNA.rds")



# scrna <- subset(x = bmcrpc, subset = cells == unique(bmcrpc$cells)[unique(bmcrpc$cells) !=c("Progenitors", "Erythroid")] )



#Create cluster and cells column in metadata 
scrna$sample <- scrna$orig.ident
scrna$cluster <- scrna$cells
scrna$cells <- scrna$barcode


scrna$cluster <- paste0(scrna$cluster, ".")
scrna@meta.data <- scrna@meta.data %>% mutate(cluster = ifelse(cluster == "CTL-1.", "CTL1.", cluster), cluster = ifelse(cluster == "CTL-2.", "CTL2.", cluster), cluster = ifelse(cluster == "Th1/17.", "Th117.", cluster), cluster = ifelse(cluster == "Treg Active.", "TregA.", cluster), cluster = ifelse(cluster == "Treg Resting.", "TregR.", cluster), cluster = ifelse(cluster == "Pro-B.", "ProB.", cluster), cluster = ifelse(cluster == "Immature B cells.", "ImmatureB.", cluster))


#Store cell types
celltypes <- scrna$cluster %>% unique()

#Store patient id
patientids <- scrna$sample %>% unique()




#cf$Tumor.Purity.Comp %>% mean()
anno$tumor_purity_wgs %>% na.omit() %>% mean()


#reference <- MakeReference(object = scrna,  tumor_bias = 0.65, number_of_cells = 10000)
reference <- MakeReference(object = scrna,  tumor_bias = 0.7, number_of_cells = 10000)



reference <- data.frame(Genes = row.names(reference[[1]]), reference[[1]])



#Format
colnames(reference) <- c("Genes", gsub(x = colnames(reference)[-1], pattern = ".[0-9]*$", replacement = ""))

write.table(reference, file = "/Users/ds/Desktop/Kfoury_bulk_reference.txt", quote = F, row.names = F, sep = "\t" )

```





#Plotting results for mCRPC deconvolution with CibersortX S-mode


```{r}


cf <- read.table("/Users/ds/Desktop/projects/BME_analysis/results/CIBERSORTx_Job33_Adjusted.txt", sep = "\t", header = T)
cf$sample_id <- gsub("\\.", "-", cf$Mixture)
row.names(cf) <- cf$Mixture

anno <- anno %>% dplyr::select(c(sample_id, wgs_id, biopsy_site,tumor_purity_wgs, tumor_purity_rna , tumor_purity_hist, disease_type_NG, ID_patient)) 

cf <- inner_join(x = cf, y = anno, by  = c("sample_id" = "sample_id"))


cf <- cf %>% mutate(Bone = ifelse(biopsy_site == "Bone", 1, 0))


row.names(cf) <- cf$sample_id


cf

```



```{r}



plot <- cf %>% dplyr::select(-c(RMSE, P.value, Correlation)) %>% gather(key = "Celltype", value = "Cell_fraction", -c(Mixture, ID_patient,wgs_id,sample_id, biopsy_site,tumor_purity_wgs, tumor_purity_wgs , tumor_purity_hist, Bone, disease_type_NG)) %>% ggplot(aes(x = Mixture, y = Cell_fraction, fill = Celltype)) + geom_col(color = "black") + xlab("Samples") + theme(axis.text.x = element_blank()) + ylim(0,1)
cf
plot

ggsave("/Users/ds/Desktop/plot.pdf", plot, width = 10)

plot <- cf %>% mutate(Sample_Index = 1:nrow(.)) %>% ggplot( aes(x = Correlation)) + geom_histogram(fill = "darkblue") + xlim(0,1)
plot

ggsave("/Users/ds/Desktop/plot.pdf", plot, width = 10)


# #Plot spearman correlation of cancer cell fraction from Cibersortx vs purity in clinical annotations
# cf <- inner_join(cf, clin, by = c("Mixture" = "WGS.Tumor.Sample.ID"))
# 
# 
# ggsave("/Users/ds/Desktop/ccf_vs_purity.pdf", plot, width = 10)
# 
# cf %>% dplyr::select(c(Mixture, Tumor, Tumor.Purity.Histo, Tumor.Purity.Comp)) %>% gather(key = mCRPC_Purity, value = Percentage, -c(Mixture, Tumor)) %>% mutate(Tumor = Tumor * 100) %>% ggplot(aes(x = Tumor, y  = Percentage, color = mCRPC_Purity)) %>% facet(facet.by = "mCRPC_Purity")+ geom_point() + stat_cor() + geom_smooth(method= "lm") + scale_color_viridis_d(end = 0.5) + xlab("Cancer cell fraction CibersortX") + ylab("Tumor Purity")
# cf

anno

plot <- cf %>% dplyr::select(c( Tumor, tumor_purity_wgs, tumor_purity_rna, tumor_purity_hist)) %>% gather(key = "Method", value = "Purity", -Tumor) %>% ggplot(aes(x = Tumor* 100, y = Purity, color = Method)) + geom_point() + geom_smooth(method = "lm") + stat_cor() + xlab("Cancer cell fraction CibersortX") + ylab("Tumor Purity")

ggsave("/Users/ds/Desktop/plot.pdf", plot, width = 10)


```




















































