---
title: "R Notebook"
output: html_notebook
---

#Format PRAD count data
```{r}

prad_meta<- mrna_query$results[[1]] %>% dplyr::filter(sample_type == "Primary Tumor")

prad_rna <- read.table(file = "/Users/ds/Desktop/projects/TCGA/TCGA-PRAD-Tumor/prad_rna_counts.txt", header = T)
prad_rna <- prad_rna[!duplicated(prad_rna$Gene),]


row.names(prad_rna) <- prad_rna$Gene 

prad_rna <- dplyr::select(prad_rna, -Gene)
keep.exprs <- filterByExpr(as.matrix(prad_rna),min.count = 5 )

prad_rna <- prad_rna[keep.exprs,]
colnames(prad_rna) <- colnames(prad_rna) %>% gsub(pattern = "^X*", replacement = "")

colnames(prad_rna) <- colnames(prad_rna) %>% gsub(pattern = "\\.", replacement = "-")

prad_rna <- edgeR::cpm(prad_rna, log = T) %>% t() %>% data.frame()#Log normalize for heatmap



prad_rna <- prad_rna %>% mutate(id = row.names(.), batch = "PRAD") %>% merge(dplyr::select(prad_meta , c(id, cases.submitter_id) ))



```



#Add PRAD purity from GDC website
```{r}
anno_prad <- read.csv(file = "/Users/ds/Desktop/projects/TCGA/TCGA-PRAD-Tumor/prad_supp.csv", header = T)
anno_prad <- anno_prad %>% dplyr::select(avgRNA_purity, PATIENT_ID, Reviewed_Gleason_sum)

prad_rna <- inner_join(prad_rna, anno_prad, by = c("cases.submitter_id" = "PATIENT_ID")) %>% mutate(Purity = avgRNA_purity * 100, cases = cases.submitter_id, Grade_Mutational_status = Reviewed_Gleason_sum)


```



```{r}

prad_anno <- read_tsv(file = "/Users/ds/Desktop/prad_tcga_clinical_data.tsv")

#prad_anno <- dplyr::select(prad_anno, c("Patient ID", "Disease Free (Months)", "Disease Free Status", "Overall Survival (Months)", "Overall Survival Status"))
prad_anno

```

```{r}

mcrpc_rna <- read.table(file = "/Users/ds/Desktop/projects/data/rna/2018_04_15_matrix_rna_counts.txt", header = T)
mcrpc_rna <- mcrpc_rna[!duplicated(mcrpc_rna$symbol),]

mcrpc_rna


row.names(mcrpc_rna) <- mcrpc_rna$symbol
mcrpc_rna <- mcrpc_rna[,-1]
keep.exprs <- filterByExpr(as.matrix(mcrpc_rna),min.count = 5 )




mcrpc_rna <- mcrpc_rna[keep.exprs,]
mcrpc_rna <- edgeR::cpm(mcrpc_rna, log = T) %>% t() %>% data.frame()#Log normalize for heatmap
#mcrpc_rna <- mcrpc_rna %>% t() %>% data.frame()#Counts for DEG analysis
row.names(mcrpc_rna) <- gsub("\\.", "-",  x = row.names(mcrpc_rna))
mcrpc_rna <- mcrpc_rna %>% mutate(cases = row.names(.), batch = "mCRPC")




```



```{r}


gex <- data.frame(Gex =rowMeans(prad_rna[,colnames(prad_rna) %in% sig.up, drop = F]) , sample_id  = prad_rna$cases.submitter_id) %>% inner_join(prad_anno, by = c("sample_id" = "Patient ID"))
gex$`Disease Free Status` <-  gex$`Disease Free Status` %>% gsub(pattern = ":.*", replacement = "") %>% as.numeric()
gex$`Overall Survival Status` <- gex$`Overall Survival Status` %>% gsub(pattern = ":.*", replacement = "") %>% as.numeric()
gex$Group <- as.factor(ntile(gex$Gex, 2))

coxph(Surv(time = `Disease Free (Months)`, event = `Disease Free Status`)~ Group , data = gex) %>% ggforest()

coxph(Surv(time = `Overall Survival (Months)`, event = `Overall Survival Status`)~ Group , data = gex) %>% ggforest()



```

```{r}



df <- mcrpc_rna[,colnames(mcrpc_rna) %in% c(tumor.down) , drop = F] %>% rowMeans() %>% data.frame(sample_id = names(.), GEX = .) 
df <- df %>% mutate(ID_patient = gsub(pattern = "-BL|-PRO|-PRO2", replacement = "", x = sample_id))  %>% inner_join(y = clin, by = c("ID_patient" = "Patient.ID"))

p1 <- coxph(Surv(time =OS.mCRPC , event = Event)~ GEX, data = df) %>% ggforest()

p2 <- coxph(Surv(time =OS.mCRPC , event = Event)~ GEX  +ECOG.PS + PSA.At.Biopsy+ LDH.at.biopsy + ALP + Hemoglobin.at.biopsy + Disease.Site + Enzalutamide.resistant  , data = df) %>% ggforest() 



```

```{r}
ggplot(gex, aes(x= Gex)) + geom_density()
ggplot(gex, aes(x =`Radical Prostatectomy Gleason Score for Prostate Cancer`, y = Gex )) + geom_point() + geom_smooth(method = 'lm') + stat_cor()

ggplot(gex, aes(x =`, y = Gex )) + geom_point() + geom_smooth(method = 'lm') + stat_cor()

gex$`Surgical Margin Resection Status`

gex <- gex[!duplicated(gex$sample_id),]

gex[duplicated(gex$sample_id),]


dplyr::filter(gex,sample_id == "TCGA-HC-8258")

```

